# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('bssid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Measurment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_value', models.IntegerField(default=0)),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Device')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='measurment',
            name='wp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Waypoint'),
        ),
    ]
