# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20160517_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurment',
            new_name='Measurement',
        ),
    ]
