# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20160517_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='dev_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='z',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ss_value',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
