# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_location_bssid'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='calibration',
            field=models.BooleanField(default=False),
        ),
    ]
