# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_measurement_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=255)),
                ('calibration', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='calibration',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='loc_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='wp_id',
        ),
        migrations.AddField(
            model_name='location',
            name='ap_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='ss_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ap_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
        migrations.AddField(
            model_name='measurement',
            name='dv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.Device'),
            preserve_default=False,
        ),
    ]
