# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20160611_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='ap_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ss_value',
        ),
    ]
