# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20160611_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_value', models.FloatField(default=0)),
                ('ap_id', models.IntegerField(default=0)),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
        ),
    ]
